#!/usr/bin/env python3
import sys
from lexer import Lexer
from parser import Parser
from compiler import Compiler

if len(sys.argv) < 2:
    print("Usage: ncc <file>")
    sys.exit(1)

file_path = sys.argv[1]

with open(file_path, "r") as f:
    source = f.read()

# Lexing
lexer = Lexer(source)
tokens, error = lexer.createTokens()
if error:
    print(error.as_string())
    sys.exit(1)

# Parsing
parser = Parser(tokens)
try:
    ast = parser.parse()
except Exception as e:
    print(f"Parse error: {e}")
    sys.exit(1)

# Compile & run
compiler = Compiler(ast)
compiler.compile_and_run()
